name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
env:
  DISCOR_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
jobs:
  Starting-discord-bot:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting python script"
      - run: python3 /main.py
