name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Starting-discord-bot:
    runs-on: ubuntu-latest
    env:
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: echo "Install discord.py"
      - run: pip install -U discord.py
      - run: echo "Install dotenv"
      - run: pip install python-dotenv
      - run: echo "Starting python script"
      - run: python3 main.py
